name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7

    - name: Verify Python version
      run: python --version

    - name: Clear pip cache
      run: python -m pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rsa pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify installed dependencies
      run: pip list

    - name: Test Python imports
      run: python -c "import rsa; import pytest; import flake8"

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: pytest
